# Generated by Django 4.2.1 on 2023-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_jobpost_created_on_jobpost_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Intern', 'Intern')], default='Full-Time', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='qualification',
            field=models.CharField(default='Bachelor of technology', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
    ]
